services:
  - type: web
    name: benue-blockchainai-fest-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
